version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  config-service:
    build: configuration_service
    ports:
      - "8000:8000"
    depends_on:
      - redis

  antivirus-service:
    build: antivirus_service
    ports:
      - "8001:8001"
    depends_on:
      - config-service
      - redis
    volumes:
      - shared-data:/to_scan
  worker:
    build: antivirus_service
    command: rq worker -c rq_settings --with-scheduler
    depends_on:
      - antivirus-service
      - redis
    volumes:
      - shared-data:/to_scan
volumes:
  shared-data:







